#-----------------------------------------------------------------------
# INTRO
[[exercises]]
name = "intro1"
path = "exercises/01_intro/intro1.nr"
mode = "test"
hint = """
No hint needed
"""

#-----------------------------------------------------------------------
# VARIABLES
[[exercises]]
name = "variables1"
path = "exercises/02_variables/variables1.nr"
mode = "test"
hint = """
Declare the variable
"""

[[exercises]]
name = "variables2"
path = "exercises/02_variables/variables2.nr"
mode = "test"
hint = """
Add a value for the variable
"""