#-----------------------------------------------------------------------
# EXAMPLES FOR CONTRIBUTORS
#[[exercises]]
#name = "example_build"
#path = "exercises/examples_for_contributors/example_build.nr"
#mode = "build"
#hint = """
#Modify the test, maybe just change one of the argument ;)
#"""
#[[exercises]]
#name = "example_execute"
#path = "exercises/examples_for_contributors/example_execute.nr"
#mode = { execute = {inlined = "a = '1' \nb = '2'"}}
#hint = """
#It should compile to ACIR and execute with a=1 and b=2. Remove the // I AM NOT DONE comment to continue
#"""
#[[exercises]]
#name = "example_execute"
#path = "exercises/examples_for_contributors/example_execute.nr"
#mode = { execute = {path = "exercises/examples_for_contributors/example_execute.toml"}}
#hint = """
#It should compile to ACIR and execute with a=1 and b=2. Remove the // I AM NOT DONE comment to continue
#"""
#[[exercises]]
#name = "example_test"
#path = "exercises/examples_for_contributors/example_test.nr"
#mode = "test"
#hint = """
#Modify the test, maybe just change one of the argument ;)
#"""
#[[exercises]]
#name = "example_bb_prove"
#path = "exercises/examples_for_contributors/example_bb_prove.nr"
#mode = { bbprove = {path = "exercises/examples_for_contributors/example_bb_prove.toml"}}
#hint = """
#It should compile to ACIR and execute with a=1 and b=2. Remove the // I AM NOT DONE comment to continue
#"""
#[[exercises]]
#name = "example_bb_verify"
#path = "exercises/examples_for_contributors/example_bb_verify.nr"
#mode = { bbverify = { save_files = false, toml_file = {path = "exercises/examples_for_contributors/example_bb_prove.toml"}}}
#hint = """
#It should compile to ACIR and execute with a=1 and b=2. Remove the // I AM NOT DONE comment to continue
#"""

#-----------------------------------------------------------------------
# INTRO
[[exercises]]
name = "intro1"
path = "exercises/01_intro/intro1.nr"
mode = "test"
hint = """
No hint needed
"""

#-----------------------------------------------------------------------
# VARIABLES
[[exercises]]
name = "variables1"
path = "exercises/02_variables/variables1.nr"
mode = "test"
hint = """
Declare the variable
"""

[[exercises]]
name = "variables2"
path = "exercises/02_variables/variables2.nr"
mode = "test"
hint = """
Add a value for the variable
"""

#-----------------------------------------------------------------------
# OPERATIONS
[[exercises]]
name = "operations1"
path = "exercises/03_operations/operations1.nr"
mode = "test"
hint = """
Add a value for the variable
"""

[[exercises]]
name = "operations2"
path = "exercises/03_operations/operations2.nr"
mode = "test"
hint = """
Add a value for the variable
"""

#-----------------------------------------------------------------------
# STRUCTS
[[exercises]]
name = "structs1"
path = "exercises/04_structs/structs1.nr"
mode = "test"
hint = """
Declare the variable
"""

[[exercises]]
name = "structs2"
path = "exercises/04_structs/structs2.nr"
mode = "test"
hint = """
"""

#-----------------------------------------------------------------------
# BIG INT
[[exercises]]
name = "bigint1"
path = "exercises/06_bigint/bigint1.nr"
mode = "test"
hint = """
"""

#-----------------------------------------------------------------------
# HASH MAPS
[[exercises]]
name = "hashmaps1"
path = "exercises/07_hash_maps/hashmaps1.nr"
mode = "test"
hint = """
Check what required fields have a hashmap
"""

[[exercises]]
name = "hashmaps2"
path = "exercises/07_hash_maps/hashmaps2.nr"
mode = "test"
hint = """
Check the 'insert' method
"""

[[exercises]]
name = "hashmaps2"
path = "exercises/07_hash_maps/hashmaps3.nr"
mode = "test"
hint = """
Check the 'get' method
"""

[[exercises]]
name = "hashmaps2"
path = "exercises/07_hash_maps/hashmaps4.nr"
mode = "test"
hint = """
Check the 'contains_key' method
"""

[[exercises]]
name = "hashmaps2"
path = "exercises/07_hash_maps/hashmaps5.nr"
mode = "test"
hint = """
Check the 'remove' method
"""

#-----------------------------------------------------------------------
# BACKEND BB
[[exercises]]
name = "bb_backend1"
path = "exercises/08_bb_backend/bb_backend1.nr"
mode = { bbprove = {path = "exercises/08_bb_backend/bb_backend1.toml"}}
hint = """
Declare the variables in the bb_backend1.toml file
"""

[[exercises]]
name = "bb_backend2"
path = "exercises/08_bb_backend/bb_backend2.nr"
mode = { bbverify = {save_files = false, toml_file = {path = "exercises/08_bb_backend/bb_backend1.toml"}}}
hint = """
Declare the variables in the bb_backend1.toml file
"""

[[exercises]]
name = "bb_recursion1"
path = "exercises/08_bb_backend/bb_recursion1.nr"
mode = { bbverify = { save_files = true, toml_file = {path = "exercises/08_bb_backend/bb_recursion1.toml"}}}
hint = """
Declare the variables in the bb_recursion1.toml file.
Don't forget to read the instruction and apply the given commands ! (inside the runner_crate folder !)
"""

[[exercises]]
name = "bb_recursion2"
path = "exercises/08_bb_backend/bb_recursion2.nr"
mode = { bbverify ={ save_files = true, toml_file={path = "exercises/08_bb_backend/bb_recursion2.toml"} } }
hint = """
Declare the variables in the bb_recursion2.toml file with the helps of the newly generated files !
Read the instructions closely ! 
"""