# INTRO

[[exercises]]
name = "intro1"
path = "exercises/1.intro/intro1.nr"
mode = { execute = "x = '1'\ny = '2'" }
hint = """
It should compile to ACIR and execute with a=1 and b=2. Remove the // I AM NOT DONE comment to continue
"""

[[exercises]]
name = "intro2"
path = "exercises/1.intro/intro2.nr"
mode = "test"
hint = """
Modify the test, maybe just change one of the argument ;)
"""

[[exercises]]
name = "intro3"
path = "exercises/1.intro/intro3.nr"
mode = "build"
hint = """
Modify the test, maybe just change one of the argument ;)
"""